###############################################################################
###############################################################################
#                                Configuration                                #
#                       Author: Christopher Reardon                           #
#                               Date 12/11/2024                               #
#                    Description: Configuration Parameters                    #
#                          Project: Phorest Analysis                          #
#                                                                             #
#                        Script Designed for Python 3                         #
#           © Copyright Christopher Reardon, Josh Male, PhorestDX             #
#                                                                             #
#                         Software Release: Unreleased                        #
###############################################################################
###############################################################################

# Sensor:
GMR_ID: Campden  # We can ignore this, it just tracks the GMR of old boxes
SENSOR_SERIAL_NUMBER: 000001
SETUP_SERIAL_NUMBER: 000001
SENSOR_TYPE: UoY

# Data:
ROOT_PATH: /home/chris/mnt/storage/Lisa/GMR/Array/250424/651/Loc1_1
DATA_PATH_FORMAT: date
IMAGE_TYPE: png
SAVE_PATH: /home/chris/mnt/storage/Lisa/GMR/Array/250424/651/Loc1_1
FIGURE_FILENAME: Lisa_ChirpArray_Ethanol

# Image:
IMAGES_METADATA_PATH: image_metadata_SU000001.json
ROI_METADATA_PATH: ROI_SU000001.json
# ANALYSIS_METHOD: max_intensity
# ANALYSIS_METHOD: centre
ANALYSIS_METHOD: gaussian
# ANALYSIS_METHOD: fano
NUMBER_SUB_ROIS: 0  # use 0 to indicate all rows

# Device:
DEVICE_SERIAL_NUMBER: '000016'
MEASUREMENT_INTERVAL: 60